### ISSUE TITLE
silent failure with [cmyk]{color}

### ISSUE THREAD

**Issue by iwelch** [ho-tex/soul#3] opened 2021-11-03 20:04 UTC
if color is loaded with cmyk, the highlight no longer works.

```
\documentclass[10pt,extrafontsizes,oneside]{memoir}

\usepackage[cmyk]{xcolor}
\usepackage{soulutf8}

\begin{document}

\hl{hello}.  can you see me?

\end{document}
```

this is one of the gotchas that take one hours to track down in complex files.  it would be great if soul could have xcolor throw an error when it tries to work with cmyk.

PS: I also wish we would place a 'deprecated' message on ctan and into the file at `soul.sty`.  I was about to report this to the author when I accidentally learned that the maintainer had become inactive.  thanks for taking this on.

**Comment by u-fischer** [comment] 2021-11-03 20:15
This is a duplicate of issue #1. And this here is the repo for soulutf8, not soul.

**Closed by u-fischer** 2021-11-03 20:15 UTC
